Form validate
mstanley-me/mobileSkeleton pull request #14
Opened 2022-02-02 15:18 UTC by mstanley-me

2022-02-02 22:39 UTC, oloomoses requested changes
Hi @mstanley-me, 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-02 22:39 UTC, oloomoses commented on script.js
> +}));
- [ ] You have done very well fixing the errors raised in the previous reviews. However, clicking the close(X) button does not close the window. Kindly ensure that When the user clicks (or taps) the close (X) button, the mobile menu disappears.

2022-02-03 05:08 UTC, mstanley-me commented on script.js
> +}));
That's good now!

2022-02-03 05:13 UTC, mateo951 approved these changes
### Hi @mstanley-me, 

Well done implementing the changes requested by the previous reviewer 👌
Your project is complete!  There is nothing else to say other than... it's time to merge it ✔ 
### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-03 05:13 UTC, mateo951 commented on script.js
> +closeMenu.addEventListener('click', close);
Addressed 🔥 The menu closes as expected when clicking the X button✔

2022-02-03 05:47 UTC, mstanley-me commented
Thank you!

On Thu, 3 Feb 2022 at 06:13, Mateo Villagomez ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> Hi @mstanley-me <https://github.com/mstanley-me>,
>
> Well done implementing the changes requested by the previous reviewer 👌
> Your project is complete! There is nothing else to say other than... it's
> time to merge it ✔
> Congratulations! 🎉
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In script.js
> <https://github.com/mstanley-me/mobileSkeleton/pull/14#discussion_r798216847>
> :
>
> > @@ -0,0 +1,21 @@
>
> +const navItems = document.querySelector('.nav-items');
>
> +const openMenu = document.querySelector('.openMenu');
>
> +const closeMenu = document.querySelector('.closeMenu');
>
> +
>
> +
>
> +openMenu.addEventListener('click', show);
>
> +closeMenu.addEventListener('click', close);
>
>
> Addressed 🔥 The menu closes as expected when clicking the X button✔
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mstanley-me/mobileSkeleton/pull/14#pullrequestreview-871370777>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVYCZFILZZMWOGTRUMQOYO3UZIFJJANCNFSM5NMKVPSQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-03 05:49 UTC, merged