Window Popup
mstanley-me/mobileSkeleton pull request #16
Opened 2022-02-03 19:45 UTC by mstanley-me

# In this milestone I:

 - implement a popup window that includes the project details in both desktop and mobile.
 - I add some change to the mobile version 

Thanks for your review😁

2022-02-03 21:12 UTC, Felipeg005 requested changes
Hi @mstanley-me, 

Good job so far 👏 !

## Highlights ✅ 
- Good Readme file
- Follows HTML good practices
- All linters passing

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-03 21:12 UTC, Felipeg005 commented on index.html
> +                            <ul class="languages">
The project's design it's looking great 💯, but when you open the project popup in the mobile version and in the desktop version there are still some issues to be fixed as I show you in the next screenshots:

## Mobile
Your design:
![image](https://user-images.githubusercontent.com/82678907/152427320-afeebf5f-3a79-41f2-81d4-2dd408bd40cf.png)

Figma Design: 
![image](https://user-images.githubusercontent.com/82678907/152427536-b3019493-1980-4639-938e-3b56dfb91909.png)

In the mobile version, the popup isn't fit on the screen and I'm not able to close or access the live and source button, for very short screen sizes you may consider to add a scroll for the popup.

- [ ] Kindly fix the popup design to make it responsive to all screen sizes.

## Desktop

Your design: 
![image](https://user-images.githubusercontent.com/82678907/152428285-af7ca753-8387-4997-9d31-5780812b2e46.png)


Figma design: 
![image](https://user-images.githubusercontent.com/82678907/152428196-4ce0e6e1-5620-49df-86ad-1a7feaaeca50.png)

In the desktop version, I'm facing the same issue.

- [ ] Kindly update your styles to follow the Figma designed and make it responsive.

2022-02-03 21:12 UTC, Felipeg005 commented on index.html
>                  <img class="work-pic" src="./images/desktop-images/img3.png" alt="landing view, desktop-image" />
Lastly but not least:

- [ ] Please add and acknowledgments section in your readme file giving credits for the design creator from Behance 😄

2022-02-03 21:43 UTC, mstanley-me commented
Hello


On Thu, 3 Feb 2022 at 22:13, Juan Felipe Gomez ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @mstanley-me <https://github.com/mstanley-me>,
>
> Good job so far 👏 !
> Highlights ✅
>
>    - Good Readme file
>    - Follows HTML good practices
>    - All linters passing
>
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/mstanley-me/mobileSkeleton/pull/16#discussion_r798958094>
> :
>
> > +                            text ever since the 1500s, when an unknown printer took a galley of type and scrambled it
>
> +                            1960s with the relea
>
> +                        </p>
>
> +                        <div class="pop-items">
>
> +                            <ul class="languages">
>
> +                                <li class="lang">html</li>
>
> +                                <li class="lang1">css</li>
>
> +                                <li class="lang2">javaScript</li>
>
> +                            </ul>
>
> +                            <div class="bottom-bar"></div>
>
> +                            <div class="navigation-links">
>
> +    <div class="btn btn-popup"><span><a href="#">See live <i class="fab fa-external-link-alt"></i></a></span></div>
>
> +    <div class="btn btn-popup"><span><a href="https://github.com/mstanley-me/mobileSkeleton">See Source <i class="fab fas-github"></i></a></span></div>
>
> +                            </div>
>
> +                        </div>
>
> +                    </div>
>
>
> You did a great HTML implementation here 👍, please remember that in this
> activity you have to create the recent works section and the pop-up for
> each work dynamically in your script.js file, using objects inside an
> array, For example:
> ```javascript const projects = [{ name: "Submarine game", description: "A
> Phaser3 plataformer game built as part of the Microverse JavaScript
> program.", image: "link_to_image.jpg", technologies: ["Phaser3",
> "JavaScript", "Jest"], link: "link_to_live_version.com", }] ```
> In that way adding projects in the future will be easier.
>
>    - Kindly add the recent works section dynamically with JavaScript
>    - Please show the popup data from the project objects with JavaScript
>
> ------------------------------
>
> In index.html
> <https://github.com/mstanley-me/mobileSkeleton/pull/16#discussion_r798967007>
> :
>
> > +                            it 1960s with the
>
> +                            releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
>
> +                            has been the industry's
>
> +                            standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
>
> +                            scrambled it 1960s with the
>
> +                            releorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
>
> +                            han printer took a galley of
>
> +                            type and scrambled it 1960s with the releawn printer took a galley of type and scrambled it
>
> +                            1960s with the releaLorem
>
> +                            Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been
>
> +                            the industry's standard dummy
>
> +                            text ever since the 1500s, when an unknown printer took a galley of type and scrambled it
>
> +                            1960s with the relea
>
> +                        </p>
>
> +                        <div class="pop-items">
>
> +                            <ul class="languages">
>
>
> The project's design it's looking great 💯, but when you open the project
> popup in the mobile version and in the desktop version there are still some
> issues to be fixed as I show you in the next screenshots:
> Mobile
>
> Your design:
> [image: image]
> <https://user-images.githubusercontent.com/82678907/152427320-afeebf5f-3a79-41f2-81d4-2dd408bd40cf.png>
>
> Figma Design:
> [image: image]
> <https://user-images.githubusercontent.com/82678907/152427536-b3019493-1980-4639-938e-3b56dfb91909.png>
>
> In the mobile version, the popup isn't fit on the screen and I'm not able
> to close or access the live and source button, for very short screen sizes
> you may consider to add a scroll for the popup.
>
>    - Kindly fix the popup design to make it responsive to all screen
>    sizes.
>
> Desktop
>
> Your design:
> [image: image]
> <https://user-images.githubusercontent.com/82678907/152428285-af7ca753-8387-4997-9d31-5780812b2e46.png>
>
> Figma design:
> [image: image]
> <https://user-images.githubusercontent.com/82678907/152428196-4ce0e6e1-5620-49df-86ad-1a7feaaeca50.png>
>
> In the desktop version, I'm facing the same issue.
>
>    - Kindly update your styles to follow the Figma designed and make it
>    responsive.
>
> ------------------------------
>
> In index.html
> <https://github.com/mstanley-me/mobileSkeleton/pull/16#discussion_r798970266>
> :
>
> >                  </div>
>
>                  <img class="work-pic-1" src="./images/desktop-images/img2.png" alt="professional art printing image" />
>
>              </div>
>
> +
>
>              <div class="container">
>
>                  <img class="work-pic" src="./images/Portoflio_Card/work2.png" alt="facebook 360 image" />
>
>                  <img class="work-pic" src="./images/desktop-images/img3.png" alt="landing view, desktop-image" />
>
>
> Lastly but not least:
>
>    - Please add and acknowledgments section in your readme file giving
>    credits for the design creator from Behance 😄
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mstanley-me/mobileSkeleton/pull/16#pullrequestreview-872397073>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVYCZFJCNKQIY3OOONJYBT3UZLVV7ANCNFSM5NP3UZ4Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-03 21:43 UTC, mstanley-me commented
Can wwe meet now please!?

On Thu, 3 Feb 2022 at 22:13, Juan Felipe Gomez ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @mstanley-me <https://github.com/mstanley-me>,
>
> Good job so far 👏 !
> Highlights ✅
>
>    - Good Readme file
>    - Follows HTML good practices
>    - All linters passing
>
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/mstanley-me/mobileSkeleton/pull/16#discussion_r798958094>
> :
>
> > +                            text ever since the 1500s, when an unknown printer took a galley of type and scrambled it
>
> +                            1960s with the relea
>
> +                        </p>
>
> +                        <div class="pop-items">
>
> +                            <ul class="languages">
>
> +                                <li class="lang">html</li>
>
> +                                <li class="lang1">css</li>
>
> +                                <li class="lang2">javaScript</li>
>
> +                            </ul>
>
> +                            <div class="bottom-bar"></div>
>
> +                            <div class="navigation-links">
>
> +    <div class="btn btn-popup"><span><a href="#">See live <i class="fab fa-external-link-alt"></i></a></span></div>
>
> +    <div class="btn btn-popup"><span><a href="https://github.com/mstanley-me/mobileSkeleton">See Source <i class="fab fas-github"></i></a></span></div>
>
> +                            </div>
>
> +                        </div>
>
> +                    </div>
>
>
> You did a great HTML implementation here 👍, please remember that in this
> activity you have to create the recent works section and the pop-up for
> each work dynamically in your script.js file, using objects inside an
> array, For example:
> ```javascript const projects = [{ name: "Submarine game", description: "A
> Phaser3 plataformer game built as part of the Microverse JavaScript
> program.", image: "link_to_image.jpg", technologies: ["Phaser3",
> "JavaScript", "Jest"], link: "link_to_live_version.com", }] ```
> In that way adding projects in the future will be easier.
>
>    - Kindly add the recent works section dynamically with JavaScript
>    - Please show the popup data from the project objects with JavaScript
>
> ------------------------------
>
> In index.html
> <https://github.com/mstanley-me/mobileSkeleton/pull/16#discussion_r798967007>
> :
>
> > +                            it 1960s with the
>
> +                            releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
>
> +                            has been the industry's
>
> +                            standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
>
> +                            scrambled it 1960s with the
>
> +                            releorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
>
> +                            han printer took a galley of
>
> +                            type and scrambled it 1960s with the releawn printer took a galley of type and scrambled it
>
> +                            1960s with the releaLorem
>
> +                            Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been
>
> +                            the industry's standard dummy
>
> +                            text ever since the 1500s, when an unknown printer took a galley of type and scrambled it
>
> +                            1960s with the relea
>
> +                        </p>
>
> +                        <div class="pop-items">
>
> +                            <ul class="languages">
>
>
> The project's design it's looking great 💯, but when you open the project
> popup in the mobile version and in the desktop version there are still some
> issues to be fixed as I show you in the next screenshots:
> Mobile
>
> Your design:
> [image: image]
> <https://user-images.githubusercontent.com/82678907/152427320-afeebf5f-3a79-41f2-81d4-2dd408bd40cf.png>
>
> Figma Design:
> [image: image]
> <https://user-images.githubusercontent.com/82678907/152427536-b3019493-1980-4639-938e-3b56dfb91909.png>
>
> In the mobile version, the popup isn't fit on the screen and I'm not able
> to close or access the live and source button, for very short screen sizes
> you may consider to add a scroll for the popup.
>
>    - Kindly fix the popup design to make it responsive to all screen
>    sizes.
>
> Desktop
>
> Your design:
> [image: image]
> <https://user-images.githubusercontent.com/82678907/152428285-af7ca753-8387-4997-9d31-5780812b2e46.png>
>
> Figma design:
> [image: image]
> <https://user-images.githubusercontent.com/82678907/152428196-4ce0e6e1-5620-49df-86ad-1a7feaaeca50.png>
>
> In the desktop version, I'm facing the same issue.
>
>    - Kindly update your styles to follow the Figma designed and make it
>    responsive.
>
> ------------------------------
>
> In index.html
> <https://github.com/mstanley-me/mobileSkeleton/pull/16#discussion_r798970266>
> :
>
> >                  </div>
>
>                  <img class="work-pic-1" src="./images/desktop-images/img2.png" alt="professional art printing image" />
>
>              </div>
>
> +
>
>              <div class="container">
>
>                  <img class="work-pic" src="./images/Portoflio_Card/work2.png" alt="facebook 360 image" />
>
>                  <img class="work-pic" src="./images/desktop-images/img3.png" alt="landing view, desktop-image" />
>
>
> Lastly but not least:
>
>    - Please add and acknowledgments section in your readme file giving
>    credits for the design creator from Behance 😄
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mstanley-me/mobileSkeleton/pull/16#pullrequestreview-872397073>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVYCZFJCNKQIY3OOONJYBT3UZLVV7ANCNFSM5NP3UZ4Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-05 18:18 UTC, t-yanick approved these changes
Hi @mstanley-me, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-05 18:20 UTC, mstanley-me commented on index.html
>                  <img class="work-pic" src="./images/desktop-images/img3.png" alt="landing view, desktop-image" />
Thank you so much i'll do that!

2022-02-05 18:21 UTC, merged